# Generated by Django 4.1.3 on 2022-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12, verbose_name='账号')),
                ('passwd', models.CharField(max_length=16, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='test_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='题目')),
                ('option_a', models.CharField(max_length=10, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=10, verbose_name='选项B')),
                ('option_c', models.CharField(max_length=10, verbose_name='选项C')),
                ('option_d', models.CharField(max_length=10, verbose_name='选项D')),
                ('answer', models.CharField(max_length=10, verbose_name='答案')),
            ],
        ),
    ]
