# Generated by Django 4.1.3 on 2022-12-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExamination', '0002_alter_admin_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='passwd',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
