# Generated by Django 4.1.5 on 2023-11-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExamination', '0005_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express_delivry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh', models.CharField(max_length=20, verbose_name='快递单号')),
                ('expre_data', models.TextField(verbose_name='快递路径')),
            ],
        ),
    ]
