# Generated by Django 4.1.5 on 2023-11-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExamination', '0006_express_delivry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='buyDate',
            field=models.CharField(max_length=100, verbose_name='购买日期'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='expectDate',
            field=models.CharField(max_length=100, verbose_name='预期到达日期'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='goonDate',
            field=models.CharField(max_length=100, verbose_name='发走日期'),
        ),
    ]
