# Generated by Django 4.1.5 on 2023-11-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExamination', '0007_alter_productdetails_buydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='kddh',
            field=models.SmallIntegerField(default=1000, verbose_name='快递单号'),
            preserve_default=False,
        ),
    ]
