# Generated by Django 4.1.5 on 2023-12-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExamination', '0009_alter_productdetails_kddh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='kddh',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='快递单号'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='pid',
            field=models.CharField(max_length=255, verbose_name='商品编号'),
        ),
    ]
