# Generated by Django 4.1.5 on 2023-12-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExamination', '0010_alter_productdetails_kddh_alter_productdetails_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='kddh',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='快递单号'),
        ),
    ]
